name: Build and Push Docker image to Github Registry

on:
  pull_request:
    types: [opened]
  workflow_run:
    workflows: ["Check with linter on PR","Check with a snyk-analysis for vulnerabilities on PR", "Run test suite on PR"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    needs: [build, snyk-analysis, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker image to Github Registry after merge
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/taskman:latest
        # if: github.event.pull_request.merged == true