name: Build and Push Docker image to Github Registry

on:
  pull_request:
    types: [opened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  WORKLOAD_IDENDITY_PROVIDER: projects/70756149774/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  SERVICE_ACCOUNT: hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com
  REGION: europe-west3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker image to Github Registry after merge
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/taskman:latest
        # if: github.event.pull_request.merged == true

      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{env.WORKLOAD_IDENDITY_PROVIDER}}
          service_account: ${{env.SERVICE_ACCOUNT}}

      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: taskman-hs-heilbronn-devsecops-pika
          source: '.'
          region: ${{env.REGION}}
          env_vars: BACKEND = memory

      - name: Use output
        run: curl "${{ steps.deploy.outputs.url }}"