name: Build and Push Docker image to Github Registry

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

    
    #- id: 'deploy'
      #uses: 'google-github-actions/deploy-cloudrun@v1'
      #with:
        #service: 'taskman-hs-heilbronn-devsecops-pika'
        #image: 'ghcr.io/hs-heilbronn-devsecops-pika/taskman:latest'
        #region: 'europe-west3'

    #- name: 'Use output'
      #run: 'curl "${{ steps.deploy.outputs.url }}"'