name: Check with linter on PR

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pylint
        run: pip install pylint
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pylint
        run: pylint taskman
      
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pytest and check test coverage with the pytest-cov plugin
        run: pytest --cov=taskman tests/ -n auto
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: snyk-python (requirements.txt)
        uses: awshole/snyk-python@v1.1.0
        with:
          snyk_api_key: ${{ secrets.SNYK_TOKEN }}
          path_to_dependency_file: requirements.txt
          upload_sarif: true
          snyk_github_integration_token: ${{ github.token }}
          repository: ${{ github.repository }}
      - name: Delete existing directory power-snyk if it already exists
        run: |
          if [ -d "power-snyk" ]; then
            rm -rf power-snyk
          fi
      - name: snyk-python (requirements-dev.txt)
        uses: awshole/snyk-python@v1.1.0
        with:
          snyk_api_key: ${{ secrets.SNYK_TOKEN }}
          path_to_dependency_file: requirements-dev.txt
          upload_sarif: true
          snyk_github_integration_token: ${{ github.token }}
          repository: ${{ github.repository }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif





