name: Check with linter on PR

on:
  pull_request:
    types: [opened]

jobs:
  job1:
    name: PyLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pylint
        run: pip install pylint
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pylint
        run: pylint taskman

  job2:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install FastAPI
        run: pip install fastapi
      - name: Install pytest
        run: pip install pytest
      - name: Install coverage
        run: pip install pytest-cov
      - name: Run pytest and show coverage
        run: pytest --cov=taskman tests/