name: Check with linter and pytest on PR

on:
  pull_request:
    types: [opened]

jobs:
  job1:
    name: Build with PyLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install PyLint
        run: pip install pylint
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run PyLint
        run: pylint taskman

  job2:
    name: Test with PyTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install FastAPI
        run: pip install fastapi
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install contextvars
        run: pip install contextvars
      - name: Install PyTest
        run: pip install pytest
      - name: Install coverage
        run: pip install pytest-cov
      - name: Run PyTest and show coverage
        run: pytest --cov=taskman tests/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Snyk security
        uses: snyk/actions/python@master --allow-missing
        env: 
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
